services:
  # -------------------------
  # Datenbank für Keycloak
  # -------------------------
  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - kc-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

  # -------------------------
  # Keycloak selbst
  # -------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_THEME_CACHE_THEMES: "false"
      KC_THEME_CACHE_TEMPLATES: "false"
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
      - ./keycloak/themes/sem-ui:/opt/keycloak/themes/sem-ui:ro
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  # -------------------------
  # App-Datenbank
  # -------------------------
  app-db:
    image: postgres:16
    container_name: app-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: nak
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  # -------------------------
  # Seminar-Service
  # -------------------------
  seminar:
    build: ../services/seminar-service
    container_name: seminar-service
    environment:
      DATABASE_URL: postgres://app:app@app-db:5432/nak
      MQ_SERVER_URL: amqp://rabbitmq
      PORT: 3000
    depends_on:
      - app-db
    ports:
      - "3000:3000"

  # -------------------------
  # Gateway
  # -------------------------
  gateway:
    build: ../gateway
    container_name: gateway
    environment:
      PORT: 8081
      OIDC_ISSUER: http://localhost:8080/realms/nak-seminar-um
      OIDC_AUDIENCE: account
      OIDC_JWKS_URI: http://keycloak:8080/realms/nak-seminar-um/protocol/openid-connect/certs
      UPSTREAM_SEMINAR: http://seminar:3000
      UPSTREAM_NOTIFICATIONS: http://notification:3001
    depends_on:
      - keycloak
      - seminar
      - notification
    ports:
      - "8081:8081"
      
  # -------------------------
  # RabbitMQ
  # -------------------------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP Port
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      RABBITMQ_LOGS: "-"
      RABBITMQ_LOG_BASE: "/var/log/rabbitmq"
      RABBITMQ_LOG_LEVEL: warning
  
  # -------------------------
  # Mailhog zum Testen von E-Mails
  # -------------------------
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025" 
      - "1025:1025" 

  notification:
    build: ../services/notification-service
    container_name: notification-service
    environment:
      DATABASE_URL: postgres://app:app@app-db:5432/nak
      MQ_SERVER_URL: amqp://rabbitmq
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      PORT: 3001
    depends_on:
      app-db:
        condition: service_started
      mailhog:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      seminar:
        condition: service_started
    ports:
      - "3001:3001"


  queue:
    build: ../services/queue-service
    container_name: queue-service
    environment:
      DATABASE_URL: postgres://app:app@app-db:5432/nak
      MQ_SERVER_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq
      - app-db
      - seminar
volumes:
  kc-db-data:
  app-db-data:
